### ISSUE TITLE
Emitting fails when interface method contains parameter CancellationToken cancellationToken = default in version 1.4.6

### ISSUE THREAD

**Issue by Husqvik** [canton7/RestEase#102] opened 2018-08-13 15:12 UTC
Occurs in 1.4.6, not in 1.4.5

`Task Foo(CancellationToken cancellationToken = default);`

Exception:
`Null is not a valid constant value for this type.`

Stack
```at System.Reflection.Emit.TypeBuilder.SetConstantValue(ModuleBuilder module, Int32 tk, Type destType, Object value)   at System.Reflection.Emit.ParameterBuilder.SetConstant(Object defaultValue)   at RestEase.Implementation.ImplementationBuilder.HandleMethods(TypeBuilder typeBuilder, Type interfaceType, FieldBuilder requesterField, FieldInfo classHeadersField, AllowAnyStatusCodeAttribute classAllowAnyStatusCodeAttribute, SerializationMethodsAttribute classSerializationMethodsAttribute, PropertyGrouping properties, MethodInfoGrouping& methodInfoGrouping)   at RestEase.Implementation.ImplementationBuilder.BuildImplementationImpl(Type interfaceType)   at RestEase.Implementation.ImplementationBuilder.CreateImplementation[T](IRequester requester)   at RestEase.RestClient.For[T](IRequester requester)```

**Comment by canton7** [comment] 2018-08-13 15:13
Duplicate of #101, already fixed in v1.4.7.

**Closed** 2018-08-18 09:53 UTC
Labels: duplicate
